name: Publish HTML

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract Branch/Tag Names
      run: |
        echo "NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9.x'

    - uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Install the Latest pip
      run: python -m pip install --upgrade pip

    - name: Install required modules
      run: python -m pip install -r requirements.txt --upgrade

    - name: Build HTML with gtag.js, and OGP tags
      env:
        GTM_ID: ${{ secrets.GTM_ID }}
        BASE_URL: https://a11y-guidelines.freee.co.jp/
      run: |
        make SPHINXOPTS="-A gtm_id=${GTM_ID} -D html_baseurl=${BASE_URL}" clean html
        cp -r ./data/json/schemas ./build/html

    - name: Publish to S3
      env:
        AWS_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      run: aws s3 sync --delete build/html/ s3://${AWS_BUCKET}/ --quiet

    - name: Prepare the HTML Archive
      run: |
        make clean html
        cp -r ./data/json/schemas ./build/html
        mv ./build/html ./freee-a11y-guidelines-${TAG}
        zip -r ${GITHUB_WORKSPACE}/freee-a11y-guidelines-${TAG}-html.zip ./freee-a11y-guidelines-${TAG}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Ver. ${{ github.ref }}
        body: |
          Release note here
        draft: true
        prerelease: false

    - name: Upload Release Artifact
      id: upload_artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/freee-a11y-guidelines-${{ env.TAG }}-html.zip
        asset_name: freee-a11y-guidelines-${{ env.TAG }}-html.zip
        asset_content_type: application/zip
